spring.application.name=backend
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://localhost:5432/clocostdb
spring.jpa.hibernate.ddl-auto=update
app.seed-data.enabled=true
